server:
  port: 10011
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka
#    registry-fetch-interval-seconds: 5
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    product-service: /item/**  # 商品微服务
    upload-service: # 文件上传微服务
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    search-service: # 搜索微服务
      path: /search/**
      serviceId: ly-search-service
      strip-prefix: false
    usercenter-service: # 用户中心
      path: /user/**
      serviceId: ly-usercenter-service
      strip-prefix: false


#  retryable: true
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  MaxAutoRetries: 0 # 同一实例的重试次数
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
#  OkToRetryOnAllOperations: true # 是否对所有操作重试
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：5000ms

