server:
  port: 8086
spring:
  application:
    name: ly-service-sms
  rabbitmq:
    virtual-host: /revan
    username: revan
    password: revan
    host: 192.168.0.110

leyou:
  sms:
    accessKeyId: LTAIc259TULYzaS7
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v
    signName: 乐优商城
    verifyCodeTemplate: SMS_148614415
