server:
  port: 8081
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 10MB # 限制文件上传的大小
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka

# FastDFS
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.0.110:22122

# 配置自定义
ly:
  upload:
    baseURL: http://image.leyou.com/
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp
