server:
  port: 8086
spring:
  application:
    name: ly-service-sms
  rabbitmq:
    host: 192.168.0.110
    virtual-host: /revan
    username: revan
    password: revan

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka

leyou:
  sms:
    accessKeyId: LTAI4FpsBDPM2pkYvhwEsPQy
    accessKeySecret: jXxhy1I8LORL3ZExlfuxGf5GShdRoQ
    signName: LVCity教育
    verifyCodeTemplate: SMS_179290464
