#设置注册服务端口
server:
  port: 8083

#设置注册服务名称
spring:
  application:
    name: ly-search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.0.110:9300
  rabbitmq:
    host: 192.168.0.110
    username: revan
    password: revan
    virtual-host: /revan

#注册服务中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}